# model settings
device: auto # Options: cuda, ,mps, cpu, auto
batch: 256
epochs: 1000

# UAV and environment settings
num_node: 4 # Number of ground nodes
area_size: 200

# Channel settings
beta_1: 10 ** (-4.643) # LoS
beta_2: 10 ** (-5.643) # NLoS
noise: 10 ** (-10.7)
power: 1

# Dataset settings
num_samples: 500000

# Model settings
hidden_N: 2000  # Number of neurons in hidden layers
hidden_L: 4  # Number of hidden layers in the neural network